### ISSUE TITLE
Implement feature to proxy recommended content

### ISSUE THREAD

**Issue by edmoz** [mozilla/embedly-proxy#122] opened 2016-06-24 16:09 UTC
This is a dependency for https://github.com/mozilla/activity-stream/issues/870

Maybe eng can meet to discuss and spec out the client-server interfaces

**Comment by edmoz** [comment] 2016-06-28 18:57
@jaredkerim : Can we get this prioritized and apply a milestone

**Comment by jaredkerim** [comment] 2016-07-19 19:34
Closing as a duplicate of #121

**Closed by jaredkerim** 2016-07-19 19:34 UTC
Labels: in progress, P1
